ALTER TABLE "CdrRequest" ADD COLUMN IF NOT EXISTS "assignedTo" TEXT;
ALTER TABLE "CdrRequest" ADD COLUMN IF NOT EXISTS "assignedAt" TIMESTAMP;
ALTER TABLE "CdrRequest" ADD CONSTRAINT "CdrRequest_assignedTo_fkey" FOREIGN KEY ("assignedTo") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
